# Generated by Django 5.2.8 on 2025-11-19 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_activity_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.CreateModel(
            name='DiscountPromotion',
            fields=[
                ('promotion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.promotion')),
                ('discount', models.SmallIntegerField()),
            ],
            bases=('store.promotion',),
        ),
    ]
