# Generated by Django 5.2.8 on 2025-11-23 00:13

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('_objects_', django.db.models.manager.Manager()),
            ],
        ),
    ]
